use School;
DROP TABLE IF EXISTS Consultations;
DROP TABLE IF EXISTS Studies;
DROP TABLE IF EXISTS Teachings;
DROP TABLE IF EXISTS Assessments;
DROP TABLE IF EXISTS Surveys;

DROP TABLE IF EXISTS Grades;
DROP TABLE IF EXISTS Teachers;
DROP TABLE IF EXISTS Students;

DROP TABLE IF EXISTS Groups;
DROP TABLE IF EXISTS Specializations;
DROP TABLE IF EXISTS Subjects;
